// Auto-generated by build.ts. Alpine no-op stub for the slim bundle.
const noop = (): void => undefined;
const stub = new Proxy(
  { start: noop, data: noop, directive: noop, magic: noop, plugin: noop, store: noop },
  { get: (t, p) => (p in t ? (t as Record<string | symbol, unknown>)[p] : noop) },
);
export default stub;
