/**
 * Bun build script. Outputs bundled JS+CSS to ../django_yp_admin/static/yp_admin/.
 *
 * Two bundles are produced:
 *   - yp-admin.js          → default; Alpine is stubbed out (dead-code-eliminated).
 *   - yp-admin-alpine.js   → full bundle including Alpine.
 *
 * The split is driven by the `__WITH_ALPINE__` define replaced at build time.
 * Because main.ts unconditionally imports `alpinejs`, we cannot fully tree-shake
 * Alpine from the default bundle without editing main.ts (owned by another
 * agent). As a stop-gap, the default bundle marks `alpinejs` as external and
 * ships a tiny inline shim that resolves the import to a no-op object, so
 * Alpine's source is excluded from the bytes the browser downloads.
 *
 * Usage:
 *   bun run build           # build both bundles
 *   bun run build --watch   # rebuild default bundle on change
 */

import { mkdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const watch = Bun.argv.includes("--watch");
const outdir = "../django_yp_admin/static/yp_admin/js";

// Tiny stub that satisfies `import Alpine from "alpinejs"` for the no-Alpine
// bundle. Alpine.start() / window.Alpine become no-ops.
const ALPINE_STUB_PATH = resolve("./.alpine-stub.ts");
mkdirSync(dirname(ALPINE_STUB_PATH), { recursive: true });
writeFileSync(
  ALPINE_STUB_PATH,
  `// Auto-generated by build.ts. Alpine no-op stub for the slim bundle.
const noop = (): void => undefined;
const stub = new Proxy(
  { start: noop, data: noop, directive: noop, magic: noop, plugin: noop, store: noop },
  { get: (t, p) => (p in t ? (t as Record<string | symbol, unknown>)[p] : noop) },
);
export default stub;
`,
);

interface BuildVariant {
  name: string;
  withAlpine: boolean;
}

async function buildVariant(variant: BuildVariant): Promise<number> {
  const outName = variant.withAlpine ? "yp-admin-alpine.js" : "yp-admin.js";

  const config: Parameters<typeof Bun.build>[0] = {
    entrypoints: ["./src/main.ts"],
    outdir,
    minify: !watch,
    sourcemap: watch ? "inline" : "none",
    target: "browser",
    format: "esm",
    naming: outName,
    define: {
      "import.meta.env.WITH_ALPINE": JSON.stringify(variant.withAlpine),
      __WITH_ALPINE__: JSON.stringify(variant.withAlpine),
    },
  };

  if (!variant.withAlpine) {
    // Redirect `alpinejs` imports to the local stub so the heavy module is
    // excluded from the slim bundle without editing main.ts.
    (config as { plugins?: unknown[] }).plugins = [
      {
        name: "alpine-stub",
        setup(build: {
          onResolve: (
            opts: { filter: RegExp },
            cb: (args: { path: string }) => { path: string },
          ) => void;
        }) {
          build.onResolve({ filter: /^alpinejs$/ }, () => ({
            path: ALPINE_STUB_PATH,
          }));
        },
      },
    ];
  }

  const result = await Bun.build(config);

  if (!result.success) {
    console.error(`Build failed (${variant.name})`);
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }

  const outPath = resolve(outdir, outName);
  const bytes = statSync(outPath).size;
  console.log(`✓ ${outName.padEnd(22)} ${(bytes / 1024).toFixed(1)} KB`);
  return bytes;
}

async function build(): Promise<void> {
  await buildVariant({ name: "slim", withAlpine: false });
  if (!watch) {
    await buildVariant({ name: "alpine", withAlpine: true });
  }
}

await build();

if (watch) {
  const watcher = (await import("node:fs")).watch(
    "./src",
    { recursive: true },
    async () => {
      console.log("Rebuilding…");
      await build();
    },
  );
  console.log("Watching ./src — Ctrl+C to stop");
  process.on("SIGINT", () => {
    watcher.close();
    process.exit(0);
  });
}
